export const bandeiras: Record<string, string> = {
  México: "🇲🇽",
  "África do Sul": "🇿🇦",
  "Coreia do Sul": "🇰🇷",
  "República Tcheca": "🇨🇿",
  Canadá: "🇨🇦",
  "Bósnia e Herzegovina": "🇧🇦",
  "Estados Unidos": "🇺🇸",
  Paraguai: "🇵🇾",
  Haiti: "🇭🇹",
  Escócia: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Brasil: "🇧🇷",
  Marrocos: "🇲🇦",
  Alemanha: "🇩🇪",
  "Costa do Marfim": "🇨🇮",
  Argentina: "🇦🇷",
  França: "🇫🇷",
  Portugal: "🇵🇹",
  Espanha: "🇪🇸",
  Uruguai: "🇺🇾",
  Bélgica: "🇧🇪",
  Holanda: "🇳🇱",
  Japão: "🇯🇵",
  Suíça: "🇨🇭",
  Colômbia: "🇨🇴",
  Inglaterra: "🏴",
  Croácia: "🇭🇷",
  Turquia: "🇹🇷",
  Austrália: "🇦🇺",
  Equador: "🇪🇨",
  Tunísia: "🇹🇳",
  Irã: "🇮🇷",
  Egito: "🇪🇬",
  "Nova Zelândia": "🇳🇿",
  Senegal: "🇸🇳",
  Noruega: "🇳🇴",
  Argélia: "🇩🇿",
  Áustria: "🇦🇹",
  Gana: "🇬🇭",
  Panamá: "🇵🇦",
  Uzbequistão: "🇺🇿",
  Catar: "🇶🇦",
  "Arábia Saudita": "🇸🇦",
  "Cabo Verde": "🇨🇻",
  Jordânia: "🇯🇴",
  Iraque: "🇮🇶",
  "República Democrática do Congo": "🇨🇩",
};